### ISSUE TITLE
Software Engineering

### ISSUE THREAD

**Issue by AyeshaIrshad1337** [hassanzhd/FAST-Resources#15]
Software engineering folder is empty and the link given is also not working

**Comment by Rubix982** [comment]
It seems as if Ian has stopped supporting the domain to keep the website up.

A solution could be go through the preface of the book and extract other mentions of links and material, or email Ian himself to look into the issue for further notice. Ian's email is ian.sommerville@st-andrews.ac.uk, extracted from https://risweb.st-andrews.ac.uk/portal/en/persons/ian-sommerville(82e68c43-14ad-4019-8099-a941bcf877d9).html.

**Comment by Rubix982** [comment]
Emailed Ian, waiting for his reply.

**Comment by AyeshaIrshad1337** [comment]
Thank you ....
